### PR TITLE
Refactor to use layout functionality in @asl/service

### PR DESCRIPTION
**Pull request by lennym**
* Moves index.jsx to layout.jsx so it is automatically used as the layout in apps which implement this module
* Sets the page component to res.template instead of res.locals.Component
* Removes explicit `wrap` prop from layout in favour of disabling wrapping in provider when an error is present

### CODE REVIEW

**Comment by lennym** [comment]
The build on this will fail until it has https://github.com/UKHomeOffice/asl-service/pull/65 merged and installed as a dev-dep

**Comment by joefitter** [comment]
💩

**Comment by lennym** [comment]
💩💥 🔫

**Comment by lennym** [comment]
👌

**Pull request merged**
