### PR TITLE
feat: [ASL-4566] PIL-E course purpose HE or training

### PR DESCRIPTION
**Pull request by kiran-varma-home-office**

### CODE REVIEW

**Review by mohomeoffice — APPROVED** [review]
seems okay to me

**Review by mohomeoffice — APPROVED** [review]
seems okay to me

**Review by jeff-horton-ho-sas — APPROVED** [review]
Note before merging this you will need to 
* Merge https://github.com/UKHomeOffice/asl-constants/pull/80
* Submit and merge a PR for asl-projects to use the new asl-constants version
* Update the dependencies here to use the new versions of asl-constants and asl-projects

**Comment by parvinba** [comment]
Build are failing, also look into that

**Review by jeff-horton-ho-sas — APPROVED** [review]

**Pull request merged**
