### PR TITLE
added collab name to success msg

### PR DESCRIPTION
**Pull request by joefitter**

### CODE REVIEW

**Comment by lennym** [comment]
Can you do the removal one too pls?

**Comment by joefitter** [comment]
there isn't one for removal - they don't get a notification

**Comment by joefitter** [comment]
or are you suggesting just having "blah has been removed."

**Comment by lennym** [comment]
It showed _something_ in S&T, and I remember seeing it and thinking "that's a bad message, it should have the name in it"

**Comment by joefitter** [comment]
sure thing, I'll get right on that (don't tell Nadia) 😆

**Pull request merged**
